name: lands
description: An absolute bare-bones web app.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  malison:
    path: ../malison
  piecemeal: 
    path: ../piecemeal

dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.1
  lints: ^2.0.0

publish_to: none
